// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvy79w-yI3FtVkLPFFbnPc7XWRQIdbIZ8',
    appId: '1:829276692771:web:ca92f55a9d0b77cf62ac96',
    messagingSenderId: '829276692771',
    projectId: 'sms-guard-patrol',
    authDomain: 'sms-guard-patrol.firebaseapp.com',
    storageBucket: 'sms-guard-patrol.appspot.com',
    measurementId: 'G-929L8PE79F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh-rzhA9-U_RVUK3iDkr_ETwoEYWKWdiA',
    appId: '1:829276692771:android:cccaf036d4cb6f7262ac96',
    messagingSenderId: '829276692771',
    projectId: 'sms-guard-patrol',
    storageBucket: 'sms-guard-patrol.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHS7BxcvHKaxeMGZAgc1DLQumHlsbxQC4',
    appId: '1:829276692771:ios:8ec0028a6c0d04da62ac96',
    messagingSenderId: '829276692771',
    projectId: 'sms-guard-patrol',
    storageBucket: 'sms-guard-patrol.appspot.com',
    iosClientId: '829276692771-lt26i85l6kb9lgle2racemshrqglumsp.apps.googleusercontent.com',
    iosBundleId: 'com.gard.sms.fltr.gardMsgFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHS7BxcvHKaxeMGZAgc1DLQumHlsbxQC4',
    appId: '1:829276692771:ios:8ec0028a6c0d04da62ac96',
    messagingSenderId: '829276692771',
    projectId: 'sms-guard-patrol',
    storageBucket: 'sms-guard-patrol.appspot.com',
    iosClientId: '829276692771-lt26i85l6kb9lgle2racemshrqglumsp.apps.googleusercontent.com',
    iosBundleId: 'com.gard.sms.fltr.gardMsgFlutter',
  );
}
